// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzbjcilgncsqctbktmoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YmpjaWxnbmNzcWN0Ymt0bW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMjQ0NzMsImV4cCI6MjA3ODcwMDQ3M30.pgywLDpp8GYS2c_PkA695dHgMcFrC94Iir85xf6dI5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});